#!/bin/bash -e

trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/postfix
  chown nobody:nogroup /var/log/postfix

  exec chpst -u nobody:nogroup svlogd /var/log/postfix
else
  exec chpst -u nobody:nogroup regex2json "^xxx"
fi
